### ISSUE TITLE
Токен не был представлен

### ISSUE THREAD

**Issue by edwardtich1** [OxFF00FF/Hamsters_mayhem#2]
"Токен не был представлен"

Все данные аккуратно ввел. Bearer и promo_id для игр
Установил на андроид

**Comment by OxFF00FF** [comment]
Другие  функции работают?

**Comment by edwardtich1** [comment]
все что не связано с токеном)

**Comment by OxFF00FF** [comment]
Значит вы наверно токен ввели в .env файле 
Или  вы не весь скопировали в браузере. 
Должно быть так
HAMSTER_TOKEN="Bearer xxx" 
Буква B большая обязательно и пробел  после B обязателен.

**Comment by edwardtich1** [comment]
HAMSTER_TOKEN="B earer 345645365436456345645634564356"
так?

**Comment by edwardtich1** [comment]
работает!!!!
что значит "отправлять в группу?"

**Comment by OxFF00FF** [comment]
> работает!!!! что значит "отправлять в группу?"

Это значит что если вы укажите в .env файле токен телеграм бота и id группы,  то сгенерированные коды отправятся в эту группу.

**Comment by edwardtich1** [comment]
APP_TOKEN="d28721be-fd2d-4b45-869e-9f253b554e50"

**Comment by OxFF00FF** [comment]
App token  и promo id уже не нужны в .env я их просто забыл убрать

**Comment by edwardtich1** [comment]
Понял. Спасибо!

**Comment by edwardtich1** [comment]
| ▱▱▱▱▱▱▰ | Сгенерированный промокод: `BIKE-0P7-FYAS-0AVD-8KW`
| ▰▰▰▰▰▰▱ | Сгенерированный промокод: `BIKE-2PB-8GKF-0ETX-VTN`
| ▰▰▰▰▱▱▱ | Сгенерированный промокод: `BIKE-0QK-B9PG-0CRD-R52`
| ▰▰▰▰▰▰▱ | Сгенерированный промокод: `BIKE-3QV-F9HG-0JVD-TJP`
Все ключи сохранены в файл `C:\Hamsters_mayhem-master\data\generated_keys (Bike Ride 3D).txt`
| ▰▰▰▰▰▰▰ | 2024-08-07 19:40:47,207 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value
| ▱▰▰▰▰▰▰ | 2024-08-07 19:40:47,447 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value
2024-08-07 19:40:47,718 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value
| ▱▱▰▰▰▰▰ | 2024-08-07 19:40:47,960 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value

**Comment by edwardtich1** [comment]
по всей видимости разработчики убрали iframe

**Comment by edwardtich1** [comment]
| ▱▰▰▰▰▰▰ | 2024-08-08 12:02:09,994 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value
| ▱▱▰▰▰▰▰ | 2024-08-08 12:02:10,212 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value
| ▱▱▱▰▰▰▰ | 2024-08-08 12:02:10,487 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value
| ▱▱▱▱▰▰▰ | 2024-08-08 12:02:10,747 - root - ERROR |  🚫  Произошла ошибка: cannot access local variable 'keys_today' where it is not associated with a value

**Comment by OxFF00FF** [comment]
нужно код обновить `git pull`

**Comment by OxFF00FF** [comment]
> > нужно код обновить `git pull`
> 
> а на Windows?

так же git pull. нужно находится в папке с проектом и чтобы был установлен git

**Comment by edwardtich1** [comment]
> > > нужно код обновить `git pull`
> > 
> > 
> > а на Windows?
> 
> так же git pull. нужно находится в папке с проектом и чтобы был установлен git

это сложно. пропущу пожалуй

**Comment by edwardtich1** [comment]
Все ключи сохранены в файл `C:\Hamsters\Hamsters_mayhem\data\generated_keys (Bike Ride 3D).txt`
| ▰▰▰▰▰▱▱ | ❌ Промоакция с ID 43e35910-c168-4634-ad4f-52fd764a843f не найдена.
| ▱▱▱▰▰▰▰ | ❌ Промоакция с ID 43e35910-c168-4634-ad4f-52fd764a843f не найдена.
| ▱▱▱▱▱▱▱ | ❌ Промоакция с ID 43e35910-c168-4634-ad4f-52fd764a843f не найдена.
| ▰▰▰▰▱▱▱ | ❌ Промоакция с ID 43e35910-c168-4634-ad4f-52fd764a843f не найдена.
| ▰▰▰▰▰▰▰ | Количество ключей для генерации (enter значение по умолчанию):

**Comment by edwardtich1** [comment]
еще при установке ругается на отсутствие файла requirements.txt

**Comment by edwardtich1** [comment]
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Hamsters\Hamsters_mayhem\Src\Hamster.py", line 743, in get_promocodes
    requests.post(f"https://api.telegram.org/bot{self.BOT_TOKEN}/sendMessage", data={"chat_id": self.GROUP_ID, "text": promocode}).raise_for_status()
  File "C:\Hamsters\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.telegram.org/botNone/sendMessage

**Comment by edwardtich1** [comment]
добытые ключи так и не вводятся в HC

**Comment by OxFF00FF** [comment]
я протестировал только что
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Хотите применить прмокоды после получения?
Y(да) / Enter(Нет): 
Количество ключей для генерации Enter(по умолчанию 1): 2
| ▱▱▱▱▱▱▱ | `Bike Ride 3D`. Генерируется ключей: 2

[1/2] `Bike Ride 3D` Getting clientId successful
[2/2] `Bike Ride 3D` Getting clientId successful
| ▰▱▱▱▱▱▱ | [2/2] `Bike Ride 3D` Login successful
| ▰▰▱▱▱▱▱ | [1/2] `Bike Ride 3D` Login successful
| ▱▰▰▰▰▰▰ | 🚴  Катаемся на велосипедах, чтобы вам не пришлось)
| ▰▰▰▰▰▱▱ | BIKE [1/2] · Статус: 20%
| ▰▰▰▰▰▰▱ | BIKE [2/2] · Статус: 20%
| ▱▱▱▱▰▰▰ | BIKE [2/2] · Статус: 40%
| ▰▰▰▰▱▱▱ | BIKE [1/2] · Статус: 40%
| ▱▱▰▰▰▰▰ | BIKE [2/2] · Статус: 60%
| ▱▱▱▱▱▱▱ | BIKE [1/2] · Статус: 60%
| ▰▰▱▱▱▱▱ | BIKE [2/2] · Статус: 80%
| ▰▱▱▱▱▱▱ | BIKE [1/2] · Статус: 80%
| ▰▰▰▱▱▱▱ | BIKE [2/2] · Статус: 100%
| ▱▱▰▰▰▰▰ | Сгенерированный промокод: `BIKE-3RH-3QE6-0FAS-CZH`
| ▰▰▰▰▰▱▱ | BIKE [1/2] · Статус: 100%
| ▱▰▰▰▰▰▰ | Сгенерированный промокод: `BIKE-0RD-5WRG-0NB9-D18`
Все ключи сохранены в файл `E:\python39\Hamsters_mayhem\data\generated_keys (Bike Ride 3D).txt`
| ▱▱▰▰▰▰▰ | Ключи были отправлены в группу `https://t.me/+mFcy-ssfgjjkiyNjYy`
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 все работает. у вас проблема с токеном скорее всего

**Comment by edwardtich1** [comment]
ключи генерируются
если бы у меня была проблема с токеном то не работали бы клики и покупка карт
а оно работает

**Comment by edwardtich1** [comment]
Хотите применить прмокоды после получения?
Y(да) / Enter(Нет): y

**Comment by edwardtich1** [comment]
или я не правильно понял и добытые ключи не попадают в HC?

**Comment by OxFF00FF** [comment]
> ключи генерируются если бы у меня была проблема с токеном то не работали бы клики и покупка карт а оно работает

хорошо, тогда можете `send_to_group = True` изменить на `send_to_group = False` чтобы по умолчанию результат не отпралялся в группу. программное переключение я еще пока не реализовал)

**Comment by OxFF00FF** [comment]
добавил что если нет токена бота то будет такое уведомление
🚫  Токен телеграм бота не указан

**Comment by edwardtich1** [comment]
> > ключи генерируются если бы у меня была проблема с токеном то не работали бы клики и покупка карт а оно работает
> 
> хорошо, тогда можете `send_to_group = True` изменить на `send_to_group = False` чтобы по умолчанию результат не отпралялся в группу. программное переключение я еще пока не реализовал)

сделал
но проблема та же

| ▰▰▰▱▱▱▱ | ❌ Промоакция с ID c4480ac7-e178-4973-8061-9ed5b2e17954 не найдена.
| ▰▰▰▰▰▰▰ | ❌ Промоакция с ID c4480ac7-e178-4973-8061-9ed5b2e17954 не найдена.
| ▱▱▱▱▰▰▰ | ❌ Промоакция с ID c4480ac7-e178-4973-8061-9ed5b2e17954 не найдена.
| ▰▰▱▱▱▱▱ | ❌ Промоакция с ID c4480ac7-e178-4973-8061-9ed5b2e17954 не найдена.

**Comment by OxFF00FF** [comment]
git pull нужно еще сделать

**Comment by OxFF00FF** [comment]
я понял в чем ошибка. постараюсь исправить

**Comment by edwardtich1** [comment]
> я понял в чем ошибка. исправил. теперь должно работать)

| ▰▰▰▰▱▱▱ | ⚠️  Активация промокода `BIKE-3RE-A43J-0QDJ-5WF`...
| ▱▱▱▱▰▰▰ | 🎉  Промокод активирован. Получено ключей сегодня: 1/4

| ▰▱▱▱▱▱▱ | ⚠️  Активация промокода `BIKE-1S6-FDBK-0DE1-Y8E`...
| ▱▰▰▰▰▰▰ | 🎉  Промокод активирован. Получено ключей сегодня: 2/4

| ▱▱▱▱▱▱▰ | ⚠️  Активация промокода `BIKE-1SY-EXCA-07CS-W0S`...
| ▰▰▰▰▰▰▱ | 🎉  Промокод активирован. Получено ключей сегодня: 3/4

| ▱▱▱▰▰▰▰ | ⚠️  Активация промокода `BIKE-0ST-8EJS-0SES-T64`...
| ▰▰▰▱▱▱▱ | 🎉  Промокод активирован. Получено ключей сегодня: 4/4

удача!

**Comment by OxFF00FF** [comment]
спасибо что помогли. я долго не понять в чем проблема)

**Comment by edwardtich1** [comment]
> поставьте лайк и друзьям скиньте, чтобы не мучились с этими играми

сомневаются в безопасности аккаунта

**Comment by edwardtich1** [comment]
при попытке генерации и ввода сразу всех кодов

Количество ключей для всех игр (enter значение по умолчанию): 4
Хотите применить прмокоды после получения?
Y(да) / Enter (Нет): y
`Bike Ride 3D`. Генерируется ключей: 4
`Chain Cube 2048`. Генерируется ключей: 4
`My Clone Army`. Генерируется ключей: 4


`Train Miner`. Генерируется ключей: 4


[1/4] `Chain Cube 2048` Getting clientId successful
[1/4] `My Clone Army` Getting clientId successful
[2/4] `Chain Cube 2048` Getting clientId successful
[1/4] `Train Miner` Getting clientId successful
[2/4] `Train Miner` Getting clientId successful
[3/4] `My Clone Army` Getting clientId successful
[2/4] `My Clone Army` Getting clientId successful
[4/4] `My Clone Army` Getting clientId successful
[1/4] `Bike Ride 3D` Getting clientId successful
[3/4] `Bike Ride 3D` Getting clientId successful
[4/4] `Train Miner` Getting clientId successful
[2/4] `Bike Ride 3D` Getting clientId successful
[3/4] `Train Miner` Getting clientId successful
[4/4] `Bike Ride 3D` Getting clientId successful
[4/4] `Chain Cube 2048` Getting clientId successful
[3/4] `Chain Cube 2048` Getting clientId successful
Exception in thread Thread-11 (__key_generation):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
Exception in thread Thread-10 (__key_generation):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
Exception in thread Thread-6 (__key_generation):
Traceback (most recent call last):
Exception in thread Thread-14 (__key_generation):
    client_token = __get_client_token(client_id)
Exception in thread Thread-13 (__key_generation):
Exception in thread Thread-15 (__key_generation):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception in thread Thread-16 (__key_generation):
Traceback (most recent call last):
    self.run()
    self.run()
    self.run()
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
  File "C:\Python312\Lib\threading.py", line 1010, in run
  File "C:\Python312\Lib\threading.py", line 1010, in run
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    response.raise_for_status()
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
    client_token = __get_client_token(client_id)
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
  File "C:\Python312\Lib\threading.py", line 1010, in run
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    raise HTTPError(http_error_msg, response=self)
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
    client_token = __get_client_token(client_id)
[2/4] `Chain Cube 2048` Login successful
[1/4] `My Clone Army` Login successful
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2/4] `My Clone Army` Login successful
    client_token = __get_client_token(client_id)
[1/4] `Bike Ride 3D` Login successful
    client_token = __get_client_token(client_id)
    client_token = __get_client_token(client_id)
[2/4] `Train Miner` Login successful
    response.raise_for_status()
[4/4] `My Clone Army` Login successful
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 665, in __key_generation
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
    response.raise_for_status()
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    response.raise_for_status()
    response.raise_for_status()
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
[3/4] `My Clone Army` Login successful
    raise HTTPError(http_error_msg, response=self)
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
[1/4] `Chain Cube 2048` Login successful
    raise HTTPError(http_error_msg, response=self)
[1/4] `Train Miner` Login successful
    raise HTTPError(http_error_msg, response=self)
    response.raise_for_status()
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client
    client_token = __get_client_token(client_id)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\Src\Hamster.py", line 642, in __get_client_token
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client
    response.raise_for_status()
  File "C:\Hamsters\Hamsters_mayhem\Hamsters_mayhem\venv\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.gamepromo.io/promo/login-client

**Comment by edwardtich1** [comment]
6 |  🚴 Промокоды Bike Ride 3D      1/4  ❌ · Осталось: 16:18:31
  7 |  🎲 Промокоды Chain Cube 2048   2/4  ❌ · Осталось: 16:18:31
  8 |  🕹  Промокоды My Clone Army     4/4  ✅ · Осталось: 16:18:31
  9 |  🚂 Промокоды Train Miner       2/4  ❌ · Осталось: 16:18:31

в итоге

**Comment by OxFF00FF** [comment]
бывает. Из за того что слишком много запросов одновременно с одного ip. Это ограничение на стороне их сервера.
попробуйте по позже и по 2 шт. У меня без проблем все 4 работают

**Comment by Alex22891** [comment]
> что ответите по безопасности?)

Могу одно сказать, вам предоставляют исходный код программы, то есть отправка ваших данных не идет не на какой сервер, кроме хамстер

**Comment by Alex22891** [comment]
2024-08-09 11:51:47,531 - root - WARNING |  🚫  Токен телеграм бота не указан  | Hamster.py - get_promocodes() - 751
2024-08-09 11:51:47,661 - root - WARNING |  🚫  Токен телеграм бота не указан  | Hamster.py - get_promocodes() - 751
2024-08-09 11:51:47,806 - root - WARNING |  🚫  Токен телеграм бота не указан  | Hamster.py - get_promocodes() - 751
2024-08-09 11:51:47,939 - root - WARNING |  🚫  Токен телеграм бота не указан  | Hamster.py - get_promocodes() - 751

Токен бота указан

**Comment by edwardtich1** [comment]
> > что ответите по безопасности?)
> 
> Могу одно сказать, вам предоставляют исходный код программы, то есть отправка ваших данных не идет не на какой сервер, кроме хамстер

Чтобы делать такие заявления нужны не просто слова а доказательства. Исходный код это конечно хорошо, но чтобы понять что в исходном коде программы не установлены параметры отправки личных данных на сторонние сервисы нужно понимать что написано в исходном коде)

**Comment by Alex22891** [comment]
> > > что ответите по безопасности?)
> > 
> > 
> > Могу одно сказать, вам предоставляют исходный код программы, то есть отправка ваших данных не идет не на какой сервер, кроме хамстер
> 
> Чтобы делать такие заявления нужны не просто слова а доказательства. Исходный код это конечно хорошо, но чтобы понять что в исходном коде программы не установлены параметры отправки личных данных на сторонние сервисы нужно понимать что написано в исходном коде)

Ну я говорю как человек который понимает в исходном коде

**Comment by OxFF00FF** [comment]
> что ответите по безопасности?)

Привет,  все в порядке,  сам пользуюсь. 
Все запросы идут только  в апи хомяка и один к апи телеграма. Никакие данные Кроме сгенерированных промокодов не сохраняются.

**Comment by edwardtich1** [comment]
> > > > что ответите по безопасности?)
> > > 
> > > 
> > > Могу одно сказать, вам предоставляют исходный код программы, то есть отправка ваших данных не идет не на какой сервер, кроме хамстер
> > 
> > 
> > Чтобы делать такие заявления нужны не просто слова а доказательства. Исходный код это конечно хорошо, но чтобы понять что в исходном коде программы не установлены параметры отправки личных данных на сторонние сервисы нужно понимать что написано в исходном коде)
> 
> Ну я говорю как человек который понимает в исходном коде

Понял. Спасибо!

**Comment by edwardtich1** [comment]
> > что ответите по безопасности?)
> 
> Привет, все в порядке, сам пользуюсь. Все запросы идут только в апи хомяка и один к апи телеграма. Никакие данные Кроме сгенерированных промокодов не сохраняются.

Спасибо!
