### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by edwardtich1** [OxFF00FF/Hamsters_mayhem#5]
2024-08-19 18:38:26,069 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/auth/account-info  | Hamster.py - login() - 838
2024-08-19 18:38:26,264 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/clicker/upgrades-for-buy  | Hamster.py - _activity_cooldowns() - 216
Traceback (most recent call last):
  File "C:\Hamsters_one\Hamsters_mayhem\main.py", line 21, in <module>
    main_menu(settings)
  File "C:\Hamsters_one\Hamsters_mayhem\Src\Menu.py", line 77, in main_menu
    for activity in activities:
TypeError: 'NoneType' object is not iterable

**Comment by OxFF00FF** [comment]
С серверами хомяка ошибка .
Еще раз попробуй  или позже

**Comment by edwardtich1** [comment]
`async def get_promocodes(self, count=4, send_to_group=False, apply_promo=False, prefix=None, save_to_file=True):`
![2024-08-19_18-47-15](https://github.com/user-attachments/assets/fea50202-7181-4ba5-8a03-54e0b96578de)

не перепутано местами?

**Comment by edwardtich1** [comment]
ошибка в меню "промокоды"
при выборе "Twerk Race" генерируются для "Train Miner"

**Comment by OxFF00FF** [comment]
> ошибка в меню "промокоды" при выборе "Twerk Race" генерируются для "Train Miner"

Исправил сегодня
